# Runs a terraform job that acts as a circuit breaker for an app receiving
# unusual (and expensive) traffic.
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "echo 'codebuild working'"