version: 0.2

# Runs a terraform job that acts as a circuit breaker for an app receiving
# unusual (and expensive) traffic.
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - terraform import -input=false aws_api_gateway_resource.test1resource1 5254ae0y7j/e87tqw
